### ISSUE TITLE
Possibility to individually assign thresholds and timeouts to gestures?

### ISSUE THREAD

**Issue by NikhilSaini38** [bulletmark/libinput-gestures#243]
I was wondering if it was possible to individually assign threshold values and intervals to gestures. there is a ruby gem called fusuma that implements it (i had been using fusuma until I found libinput-gestures). Check it out at https://github.com/iberianpig/fusuma.
I want to implement 3 and 4 finger pinches and rotations and fusuma doesn't seem to have support for that. I want some gestures to be highly sensitive and others not as much. What am I missing?
My YAML config for fusuma might give an idea what I am looking to implement

```
swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
    up:
      command: 'xdotool key XF86AudioRaiseVolume'
      threshold: 0.05
      interval: 0.05
    down:
      command: 'xdotool key XF86AudioLowerVolume'
      threshold: 0.05
      interval: 0.05
  4:
    left:
      command: 'xdotool key ctrl+super+Right'
    right:
      command: 'xdotool key ctrl+super+Left'
    up:
      command: 'xdotool key XF86MonBrightnessUp'
      threshold: 0.05
      interval: 0.05
    down:
      command: 'xdotool key XF86MonBrightnessDown'
      threshold: 0.05
      interval: 0.05
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
      threshold: 0.1
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: 0.5
  pinch: 0.5

interval:
  swipe: 0.5
  pinch: 0.5
```
